# basic
title: fpgayu
subtitle: 左手程序，右手诗
favicon: favicon.ico

# avatar: images/avatar.png
# banner_small: images/banner-small.png
# banner_large: images/banner-large.png
avatar: https://s1.ax1x.com/2018/02/02/9EiXYn.png
banner_small: https://s1.ax1x.com/2018/02/02/9EC4AA.jpg
banner_large: https://s1.ax1x.com/2018/02/02/9EC4AA.jpg
# disqus
disqus_shortname: drakeleung

# social
social:
  github: https://github.com/fpagyu
  twitter: https://twitter.com/DrakeLeung
  weibo: http://weibo.com/cha12chalyc

# nav #
nav:
  home: .
  archive: archives
  # about: about
  rss: atom.xml

# heox-renderre-sass
node_sass:
  outputStyle: nested
  precision: 5
  sourceComments: false


google_analytics: # Put tracking ID here
